### ISSUE TITLE
Bug in _mm_loadu_si64() replacement

### ISSUE THREAD

**Issue by fwojcik** [Keith-Cancel/k-hashv#2]
On line 460 in khashv.h, the code to implement `_mm_loadu_si64()` uses `_mm_cvtsi32_si128(val)` instead of `_mm_cvtsi64_si128(val)`, which causes input bytes to be truncated and incorrect hashes to be computed.

**Comment by Keith-Cancel** [comment]
Oh glad you noticed that! Fixed it.
