### ISSUE TITLE
Please add a SMHasher3 link to README.md

### ISSUE THREAD

**Issue by fwojcik** [Keith-Cancel/k-hashv#4]
I would really appreciate it if you also mentioned my SMHasher3 project in your README.md and added a link to it (https://gitlab.com/fwojcik/smhasher3/). Thank you.

**Comment by Keith-Cancel** [comment]
Easy enough. https://github.com/Keith-Cancel/k-hashv/commit/59ec8709dbb2ab97a7db1ab04ce494d72be634ed
